### ISSUE TITLE
Incorrect Port on prometheus.yml for speedtest

### ISSUE THREAD

**Issue by cinntech** [danopstech/starlink#9]
- job_name: 'speedtest'    scrape_interval: 60m    scrape_timeout: 70s    static_configs:      - targets: [ 'speedtest_exporter:9090' ]

Should be:
  - job_name: 'speedtest'    scrape_interval: 60m    scrape_timeout: 70s    static_configs:      - targets: [ 'speedtest_exporter:9092' ]

**Comment by dwillcocks** [comment]
I'm struggling to find the bug here. speedtest exporter is listening on 9090 within the docker bridge network. it is then mapped out to 9092 onto the host so users can access its simple root page. prometheus is accessing/scraping it via the bridge network on `speedtest_exporter:9090` with is correct and works.

I have not allocated a port on https://github.com/prometheus/prometheus/wiki/Default-port-allocations so the container has been defaulted to 9090. then it can be mapped out accordingly.

**Comment by cinntech** [comment]
Bug was on my side with conflict with another dock (it worked when I changed the port). Closing issue.
